### ISSUE TITLE
Error: No net configs found

### ISSUE THREAD

**Issue by karandwivedi42** [han-cai/PathLevel-EAS#1]
Hi

I am seeing the following error when I try to run the following command:

```
python arch_search.py --setting pyramidnet-cell
```

Error:

```
Traceback (most recent call last):
  File "arch_search.py", line 44, in <module>
    virtual=False,
  File "/home/karan/PathLevel-EAS/code/CIFAR/arch_search/arch_search_tree_cell.py", line 233, in arch_search_tree_cell
    arch_manager = ArchManager(arch_search_folder, exp_settings, batch_num_per_update, reward_config, random=random)
  File "/home/karan/PathLevel-EAS/code/CIFAR/expdir_monitor/arch_manager.py", line 54, in __init__
    model = start_net_monitor.load_model(print_info=True)
  File "/home/karan/PathLevel-EAS/code/CIFAR/expdir_monitor/expdir_monitor.py", line 114, in load_model
    assert os.path.isfile(self.net_config_path), 'No net configs found in <%s>' % self.expdir
AssertionError: No net configs found in </home/karan/PathLevel-EAS/code/CIFAR/placeholderStartNets/PyramidNet/placeholder>
```

**Comment by han-cai** [comment]
Notice that the folder name in “arch_search.py” is “placeholder”. You need to replace it with a folder that has “init” and “net.config”. To get such folders, please refer to “run_pyramid.py” or "run_densenet.py".

**Comment by karandwivedi42** [comment]
Thanks!

**Comment by sxs11** [comment]
Hi, I don't understand how to replace the "placeholder", and what is "init" and "net.config"?
Could you help me with that?
